### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large

### ISSUE THREAD

**Issue by kleinsbotle** [UNICT-Fake-Audio/fake-audio-detector#3]
Hello and thank you for your work!
I've encountered a problem: I use [Multi-Tacotron voice cloning](https://github.com/vlomme/Multi-Tacotron-Voice-Cloning?ysclid=l8u4bxyxr4513046867) to synthesize speech samples and then try to check if they are fake with your script, but I keep getting this error:
`/home/efg/anaconda3/lib/python3.9/site-packages/spafe/frequencies/fundamental_frequencies.py:53: RuntimeWarning: invalid value encountered in true_divide
     cmndf = df[1:] * range(1, N) / np.cumsum(df[1:]).astype(`
`/home/efg/anaconda3/lib/python3.9/site-packages/spafe/features/msrcc.py:115: RuntimeWarning: divide by zero encountered in power
   features = features**gamma`
`/home/efg/anaconda3/lib/python3.9/site-packages/spafe/utils/cepstral.py:28: RuntimeWarning: invalid value encountered in subtract
  return x - np.mean(x, axis=0)`
`/home/efg/anaconda3/lib/python3.9/site-packages/spafe/features/psrcc.py:117: RuntimeWarning: divide by zero encountered in power
  features = features**gamma`
`Traceback (most recent call last):`
  `File "/home/efg/Desktop/ml/speech/fake-audio-detector/main.py", line 10, in <module>
    results = model.predict([sample_features])`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_weight_boosting.py", line 679, in predict
    pred = self.decision_function(X)`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_weight_boosting.py", line 747, in decision_function
    pred = sum(`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_weight_boosting.py", line 748, in <genexpr>
    _samme_proba(estimator, n_classes, X) for estimator in self.estimators_`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_weight_boosting.py", line 300, in _samme_proba
    proba = estimator.predict_proba(X)`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 971, in predict_proba
    X = self._validate_X_predict(X, check_input)`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 433, in _validate_X_predict
    X = self._validate_data(X, dtype=DTYPE, accept_sparse="csr", reset=False)`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/base.py", line 561, in _validate_data
    X = check_array(X, **check_params)`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 792, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")`
  `File "/home/efg/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(`
`ValueError: Input contains NaN, infinity or a value too large for dtype('float32').`

What could I do to solve this problem?
I also attach the [link](https://dropmefiles.com/OoKmM) to one of the sample files I tried to test.

**Comment by Helias** [comment]
I think it's the wav format, if you convert it using Audactiy you can make it work. It detects the sample as fake.

Keep in mind that the detector is a prototype used for ASVspoof dataset, so it's not sure that is accurate for all kind of synthetic voices.

[demo_output_00.wav.zip](https://github.com/UNICT-Fake-Audio/fake-audio-detector/files/9891808/demo_output_00.wav.zip)
