### ISSUE TITLE
Error input 

### ISSUE THREAD

**Issue by chiarapero1993** [UNICT-Fake-Audio/fake-audio-detector#6]
The script main.py only works with the audios provided in the Data folder.
Providing .wav audio as input gives the following error:

feats["peak_frequency"] = frequencies[np.argmax(amplitudes)]
IndexError: index 8795568 is out of bounds for axis 0 with size 44960

**Comment by Helias** [comment]
mhm, not sure about the nature of the issue, try to convert your audio from multiple channels to one channel

`ffmpeg -i input.wav -ac 1 output.wav`

**Comment by chiarapero1993** [comment]
Thanks :-) now it works but classifies everything as fake...

**Comment by Helias** [comment]
it's an issue that I should handle in these models, I hope to release this year new models.
